<a href="https://colab.research.google.com/github/aliyusifov99/ml_course_utp/blob/main/Numpy_%26_Pandas_%26_Matplotlib.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy

In [2]:
import numpy as np

In [3]:
x = np.array([1,2,3,4,5])
x

array([1, 2, 3, 4, 5])

In [4]:
2 * (x + 3)

array([ 8, 10, 12, 14, 16])

In [5]:
y = [1,2,3,4,5]
y

[1, 2, 3, 4, 5]

In [6]:
2 * (y + 3)

TypeError: ignored

## Multidimensional Arrays

In [8]:
x = np.array([[1,2,3], [4,5,6]])
x

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
x.ndim


2

In [10]:
x.shape

(2, 3)

In [11]:
x.size

6

In [12]:
x.dtype

dtype('int64')

## Array Creation

In [13]:
np.zeros((2,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [14]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

Question: How would you get a matrix all 2s? Shape should be 3x3

In [15]:
np.ones((3,3)) * 2

array([[2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.]])

In [16]:
np.ones((3,3), dtype=np.float64)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [17]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [25]:
np.linspace(1,10,20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

## Array indexing and slicing

In [26]:
x = np.array([1,2,3,4,5])
x[3]

4

In [27]:
x[:3]

array([1, 2, 3])

In [28]:
y[3:]

[4, 5]

In [29]:
x[::-1]

array([5, 4, 3, 2, 1])

In [30]:
x = np.array([1,2,3,4,5,6,7,8,9,10])
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [33]:
x= x.reshape(2,5)
x

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [34]:
x[1]

array([ 6,  7,  8,  9, 10])

In [35]:
x[0][1]

2

In [38]:
x[:,1:3]

array([[2, 3],
       [7, 8]])

In [39]:
x.reshape(-1,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])

In [40]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [42]:
np.ones(12).reshape(3,4)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [43]:
x = np.arange(10)
y = np.arange(10,20)

In [44]:
x + y

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [45]:
x - y

array([-10, -10, -10, -10, -10, -10, -10, -10, -10, -10])

In [46]:
x * y

array([  0,  11,  24,  39,  56,  75,  96, 119, 144, 171])

## Math Functions

In [49]:
np.sqrt(x)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [51]:
np.log(y)

array([2.30258509, 2.39789527, 2.48490665, 2.56494936, 2.63905733,
       2.7080502 , 2.77258872, 2.83321334, 2.89037176, 2.94443898])

In [52]:
np.sin(x)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [53]:
np.array([1, 2, 3, 4]).astype(float)

array([1., 2., 3., 4.])

In [54]:
np.array([1, 0, 1, 1, 0, 0]).astype(bool)

array([ True, False,  True,  True, False, False])

In [55]:
x.min()

0

In [56]:
x.max()

9

In [57]:
x.mean()

4.5

In [60]:
np.max(x)

9

In [62]:
np.min(x)

0

In [63]:
np.median(x)

4.5

In [64]:
np.std(x)

2.8722813232690143

In [65]:
x.sum()

45

## Axes

In [67]:
x = np.arange(60).reshape(3,4,5)
x

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]],

       [[40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59]]])

In [68]:
x.sum()

1770

In [69]:
x.sum(axis=0)

array([[ 60,  63,  66,  69,  72],
       [ 75,  78,  81,  84,  87],
       [ 90,  93,  96,  99, 102],
       [105, 108, 111, 114, 117]])

In [70]:
x.sum(axis=1)

array([[ 30,  34,  38,  42,  46],
       [110, 114, 118, 122, 126],
       [190, 194, 198, 202, 206]])

In [71]:
x.sum(axis=2)

array([[ 10,  35,  60,  85],
       [110, 135, 160, 185],
       [210, 235, 260, 285]])

## Concatenating arrays

In [72]:
x = np.array([1,2,3])
y = np.array([4,5,6])

In [73]:
np.concatenate([x,y])

array([1, 2, 3, 4, 5, 6])

In [74]:

np.concatenate([x, y, np.ones(10)])

array([1., 2., 3., 4., 5., 6., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [76]:
np.hstack([x,y])

array([1, 2, 3, 4, 5, 6])

In [77]:
np.vstack([x,y])

array([[1, 2, 3],
       [4, 5, 6]])

## Copying arrays

In [80]:
x = np.arange(10)
x[0] = 100
x

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [81]:
y = x

In [82]:
y[0] = -50

In [83]:
y

array([-50,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [84]:
x

array([-50,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [85]:
y = x.copy()

In [86]:
y[0] = 200
y

array([200,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [87]:
x

array([-50,   1,   2,   3,   4,   5,   6,   7,   8,   9])

## Boolean Array Indexing

In [89]:
x = np.arange(20)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [90]:
x < 10

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False, False, False, False, False, False, False, False,
       False, False])

In [91]:
x[x < 10]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [92]:
x[(x < 10) & (x % 2 == 0)]

array([0, 2, 4, 6, 8])

## Numpy random module

In [93]:
np.random.random(size=10)

array([0.55368882, 0.36531921, 0.94822176, 0.01337074, 0.88016995,
       0.71597306, 0.97384047, 0.32062073, 0.62000781, 0.91227815])

In [94]:
np.random.random(size=(5,5))

array([[0.74638824, 0.69795452, 0.01580907, 0.64607384, 0.50160823],
       [0.2654232 , 0.2623051 , 0.83683145, 0.22507223, 0.1685731 ],
       [0.97662362, 0.7492839 , 0.57933515, 0.77908842, 0.4548225 ],
       [0.90077981, 0.65504858, 0.75298732, 0.82124317, 0.65750825],
       [0.07207163, 0.6604049 , 0.45486542, 0.15002207, 0.76676673]])

## Argmin, argmax, argsort

In [95]:
x = np.random.randint(10,100, size=20)
x

array([32, 21, 15, 48, 50, 44, 77, 17, 86, 41, 12, 56, 60, 99, 97, 24, 55,
       89, 88, 29])

In [96]:
x.min()

12

In [97]:
x.argmin()

10

In [98]:
x[10]

12

In [99]:
x[x.argmin()]

12

In [100]:
x[x.argsort()]

array([12, 15, 17, 21, 24, 29, 32, 41, 44, 48, 50, 55, 56, 60, 77, 86, 88,
       89, 97, 99])

## Saving/Loading array files

In [101]:
np.save('my_array', x)


In [102]:
y = np.load('my_array.npy')

In [103]:
y

array([32, 21, 15, 48, 50, 44, 77, 17, 86, 41, 12, 56, 60, 99, 97, 24, 55,
       89, 88, 29])

## Matrix operations

In [104]:
x = np.arange(12).reshape(3, -1)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [106]:
y = x.T

In [108]:
x @ y

array([[ 14,  38,  62],
       [ 38, 126, 214],
       [ 62, 214, 366]])

In [109]:
y @ x

array([[ 80,  92, 104, 116],
       [ 92, 107, 122, 137],
       [104, 122, 140, 158],
       [116, 137, 158, 179]])

# Pandas

In [110]:
import pandas as pd

In [113]:
df = pd.DataFrame([{'element': 'Helium', 'symbol': 'He', 'atomic_number': 2},
    {'element': 'Magnesium', 'symbol': 'Mg', 'atomic_number': 12}])

In [115]:
df

element symbol  atomic_number
0     Helium     He              2
1  Magnesium     Mg             12

In [116]:
df.columns

Index(['element', 'symbol', 'atomic_number'], dtype='object')

In [117]:
df.shape

(2, 3)

In [118]:
df['element']

0       Helium
1    Magnesium
Name: element, dtype: object

In [119]:
df[['element', 'symbol']]

element symbol
0     Helium     He
1  Magnesium     Mg

In [120]:
pd.Series([1000,2000,3000], name='price')

0    1000
1    2000
2    3000
Name: price, dtype: int64

In [121]:
df['symbol']

0    He
1    Mg
Name: symbol, dtype: object

## Type casts

# Matplotlib

# Seaborn